package Vista;

import Controlador.AnulacionesControl;
import Controlador.Cronometro;
import Controlador.ManejadorFechas;
import Controlador.MyiReportVisor;
import Modelo.FlujoCajaDAO;
import Modelo.VentaDAO;
import Modelo.VentaProductoDAO;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * Grøver R£ndiÇh
 */
public class Anulaciones extends javax.swing.JFrame {

    MyiReportVisor mrv;
    HashMap parametros = new HashMap();
    Integer num = 1;

    public Anulaciones(String Usuario) {
        initComponents();
        setLocationRelativeTo(null);
        datosIniciales(Usuario);
    }

    public Anulaciones() {
    }

    public void datosIniciales(String Usuario) {
        try {
            lblUsuario.setText(Usuario);
            lblFecha.setText(new ManejadorFechas().getFechaActual());
            lblCaja.setText(new AnulacionesControl().getCajaDeUsuario(Usuario));
            new Cronometro().iniciarCronometro(txtHoraCronometro);
            new AnulacionesControl().cargarTitulosTabla(tblDetalle);
            //int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new GastosControl().getIdUsuario(lblUsuario.getText()), new GastosControl().getIdCaja(lblCaja.getText()));
            switch (lblCaja.getText()) {
                case "GENERAL 1":
                    num = 1;
                    break;
                case "GENERAL 2":
                    num = 2;
                    break;
                case "VIP":
                    num = 3;
                    break;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    Connection Connection;
    PreparedStatement PreparedStatement;
    ResultSet ResultSet;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConceptoAnulacion = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaConceptoAnulacion = new javax.swing.JTextArea();
        btnConceptoAnulacion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnAnular = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        txtnumVenta = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_num_venta = new javax.swing.JTextField();
        btnListaAnulaciones = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCaja = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHoraCronometro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panelEstado = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtTipoVenta = new javax.swing.JTextField();
        btnBuscarNotaPedido = new javax.swing.JButton();

        panelConceptoAnulacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INGRESE CONCEPTO DE ANULACION DE BOLETA");
        panelConceptoAnulacion.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 30));

        txaConceptoAnulacion.setColumns(20);
        txaConceptoAnulacion.setLineWrap(true);
        txaConceptoAnulacion.setRows(5);
        jScrollPane2.setViewportView(txaConceptoAnulacion);

        panelConceptoAnulacion.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 420, 260));

        btnConceptoAnulacion.setBackground(new java.awt.Color(0, 102, 0));
        btnConceptoAnulacion.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnConceptoAnulacion.setForeground(new java.awt.Color(255, 255, 255));
        btnConceptoAnulacion.setText("ANULAR");
        btnConceptoAnulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConceptoAnulacionActionPerformed(evt);
            }
        });
        panelConceptoAnulacion.getContentPane().add(btnConceptoAnulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 420, 60));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelConceptoAnulacion.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 420, -1));

        setTitle("Anulaciones");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("CAJA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 110, -1));

        txtCaja.setEditable(false);
        txtCaja.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtCaja.setForeground(new java.awt.Color(0, 102, 204));
        txtCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCaja.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 220, -1));

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("USUARIO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 110, -1));

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("CONCEPTO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 110, -1));

        txtHora.setEditable(false);
        txtHora.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtHora.setForeground(new java.awt.Color(0, 102, 204));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 220, -1));

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("TIPO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, 110, -1));

        btnAnular.setBackground(new java.awt.Color(255, 0, 0));
        btnAnular.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        btnAnular.setForeground(new java.awt.Color(255, 255, 255));
        btnAnular.setText("ANULAR");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 720, 280, 70));

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel17.setText("S/.");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, -1, -1));

        txtMonto.setBackground(new java.awt.Color(240, 240, 240));
        txtMonto.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 280, 70));

        jLabel18.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel18.setText("MONTO");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, -1, -1));

        jLabel19.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("HORA");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 110, -1));

        jLabel20.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("DETALLE DE VENTA");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 100, -1));

        txtConcepto.setEditable(false);
        txtConcepto.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtConcepto.setForeground(new java.awt.Color(0, 102, 204));
        txtConcepto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConcepto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 220, -1));

        txtnumVenta.setEditable(false);
        txtnumVenta.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtnumVenta.setForeground(new java.awt.Color(0, 102, 204));
        txtnumVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnumVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtnumVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 220, -1));

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 102, 204));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 220, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn7.setBackground(new java.awt.Color(0, 153, 255));
        btn7.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorderPainted(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setFocusPainted(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 110, 100));

        btn8.setBackground(new java.awt.Color(0, 153, 255));
        btn8.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorderPainted(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setFocusPainted(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, 100));

        btn9.setBackground(new java.awt.Color(0, 153, 255));
        btn9.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorderPainted(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setFocusPainted(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 110, 100));

        btn4.setBackground(new java.awt.Color(0, 153, 255));
        btn4.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorderPainted(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setFocusPainted(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 100));

        btn5.setBackground(new java.awt.Color(0, 153, 255));
        btn5.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorderPainted(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setFocusPainted(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 110, 100));

        btn6.setBackground(new java.awt.Color(0, 153, 255));
        btn6.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorderPainted(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setFocusPainted(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 110, 100));

        btn1.setBackground(new java.awt.Color(0, 153, 255));
        btn1.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorderPainted(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setFocusPainted(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 110, 100));

        btn2.setBackground(new java.awt.Color(0, 153, 255));
        btn2.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorderPainted(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setFocusPainted(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 110, 100));

        btn3.setBackground(new java.awt.Color(0, 153, 255));
        btn3.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorderPainted(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setFocusPainted(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 110, 100));

        btn0.setBackground(new java.awt.Color(0, 153, 255));
        btn0.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorderPainted(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setFocusPainted(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 110, 100));

        btnDel.setBackground(new java.awt.Color(255, 0, 0));
        btnDel.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("x");
        btnDel.setBorderPainted(false);
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.setFocusPainted(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 110, 100));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("N° BOLETA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        txt_num_venta.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txt_num_venta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txt_num_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 350, 50));

        btnListaAnulaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListaAnulaciones.setText("LISTA DE ANULACIONES");
        btnListaAnulaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaAnulacionesActionPerformed(evt);
            }
        });
        jPanel2.add(btnListaAnulaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 350, 70));

        btnBuscar.setBackground(new java.awt.Color(0, 204, 51));
        btnBuscar.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorderPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 110, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 430, 650));

        txtUsuario.setEditable(false);
        txtUsuario.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 102, 204));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 220, -1));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ANULACIONES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1340, 60));

        lblCaja.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCaja.setForeground(new java.awt.Color(255, 255, 255));
        lblCaja.setText("__________");
        jPanel1.add(lblCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 240, -1));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("_______");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 210, -1));

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("_____");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 120, 160, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FECHA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HORA:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, -1, -1));

        txtHoraCronometro.setEditable(false);
        txtHoraCronometro.setBackground(new java.awt.Color(255, 51, 51));
        txtHoraCronometro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtHoraCronometro.setForeground(new java.awt.Color(255, 255, 255));
        txtHoraCronometro.setText("______");
        jPanel1.add(txtHoraCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 120, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USUARIO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CAJA:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 160));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 890, 190));

        jLabel1.setText("ESTADO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 20));

        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEstado.setText("____________________");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 210, 20));

        jLabel21.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("N° VENTA");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 110, -1));
        getContentPane().add(panelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 620, 20));

        jLabel16.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("FECHA");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 110, -1));

        txtTipoVenta.setEditable(false);
        txtTipoVenta.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtTipoVenta.setForeground(new java.awt.Color(0, 102, 204));
        txtTipoVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtTipoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 220, -1));

        btnBuscarNotaPedido.setBackground(new java.awt.Color(204, 102, 0));
        btnBuscarNotaPedido.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        btnBuscarNotaPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarNotaPedido.setText("BUSCAR Nota Pedido");
        btnBuscarNotaPedido.setBorderPainted(false);
        btnBuscarNotaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNotaPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarNotaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 720, 310, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        try {
            if (!txt_num_venta.getText().trim().isEmpty()) {
                if (lblCaja.getText().equals(txtCaja.getText())) {
                    panelConceptoAnulacion.setVisible(true);
                    panelConceptoAnulacion.setBounds(700, 250, 435, 431);
                } else {
                    JOptionPane.showMessageDialog(getRootPane(), "EL NUMERO DE BOLETA CORRESPONDE A OTRA CAJA");
                }
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "INGRESE NUMERO DE BOLETA");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String captura = txt_num_venta.getText() + 7;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String captura = txt_num_venta.getText() + 8;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String captura = txt_num_venta.getText() + 9;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String captura = txt_num_venta.getText() + 4;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String captura = txt_num_venta.getText() + 5;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String captura = txt_num_venta.getText() + 6;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String captura = txt_num_venta.getText() + 1;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String captura = txt_num_venta.getText() + 2;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String captura = txt_num_venta.getText() + 3;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String captura = txt_num_venta.getText() + 0;
        txt_num_venta.setText(captura);

    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        txt_num_venta.setText("");
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int numBoleta = Integer.parseInt(txt_num_venta.getText());
            if (new AnulacionesControl().getEstadoDeVenta(numBoleta, num)) {
                lblEstado.setText("ACTIVO");
                //lblEstado.setBackground(Color.GREEN);
                panelEstado.setBackground(Color.GREEN);
            } else {
                lblEstado.setText("ANULADO");
                //lblEstado.setBackground(Color.RED);
                panelEstado.setBackground(Color.RED);
            }

            AnulacionesControl ac = new AnulacionesControl();
            //String datos[] = new String[5];
            String array[] = ac.CargarDatos(numBoleta, num);
            txtnumVenta.setText(array[0]);
            txtConcepto.setText(array[1]);
            txtCaja.setText(new AnulacionesControl().getCajaConId(Integer.parseInt(array[2])));
            //txtUsuario.setText(array[3]);
            txtUsuario.setText(new AnulacionesControl().getNomUsuario(Integer.parseInt(array[3])));
            txtHora.setText(array[4]);
            txtFecha.setText(array[5]);
            txtTipoVenta.setText(array[6]);
            txtMonto.setText("" + new VentaProductoDAO().getMontoDeVenta(numBoleta, num));
            int idAlmacen = 2;
            switch (txtCaja.getText()) {
                case "VIP":
                    idAlmacen = 3;
                    break;
            }

            new AnulacionesControl().cargarTabla(numBoleta, tblDetalle, num, idAlmacen);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListaAnulacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaAnulacionesActionPerformed
        try {
            int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new AnulacionesControl().getIdUsuario(lblUsuario.getText()), new AnulacionesControl().getIdCaja(lblCaja.getText()));
            System.out.println(idFlujoCaja);
//            parametros.put("Usuario", txtUsuario.getText());
//            parametros.put("Caja", txtCaja.getText());
            parametros.put("idFlujo", idFlujoCaja);
            mrv = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\Anulaciones" + num + ".jrxml", parametros);
            mrv.exportarAPdf();
        } catch (Exception ex) {
            Logger.getLogger(Anulaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListaAnulacionesActionPerformed

    private void btnConceptoAnulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConceptoAnulacionActionPerformed
        try {
            int numVenta = Integer.parseInt(txt_num_venta.getText());
            if (new VentaDAO().anular(numVenta, num)) {
                new AnulacionesControl().sumarStock(tblDetalle,1);//1= anular venta real
                new VentaProductoDAO().updateVentaProducto(numVenta, num);
                if (txtTipoVenta.getText().equals("4")) {
                    new VentaProductoDAO().updateVentaProductoOP(numVenta, num);
                }
                JOptionPane.showMessageDialog(getRootPane(), "LA VENTA: " + numVenta + " FUE ANULADA EXITOSAMENTE");
                panelConceptoAnulacion.dispose();
                //limpiarCampos();
//                JPanel temp=(JPanel) this.getContentPane(); 
//                SwingUtilities.updateComponentTreeUI(temp);
//                this.validateTree();
            } else {
                System.out.println("error");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnConceptoAnulacionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        panelConceptoAnulacion.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBuscarNotaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNotaPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarNotaPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anulaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarNotaPedido;
    private javax.swing.JButton btnConceptoAnulacion;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnListaAnulaciones;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCaja;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JDialog panelConceptoAnulacion;
    private javax.swing.JPanel panelEstado;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextArea txaConceptoAnulacion;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtHoraCronometro;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtTipoVenta;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txt_num_venta;
    private javax.swing.JTextField txtnumVenta;
    // End of variables declaration//GEN-END:variables

    public void limpiarCampos() {
        txt_num_venta.setText("");
        lblEstado.setText("");
        new AnulacionesControl().limpiarTabla(tblDetalle);
        panelEstado.setBackground(new Color(240, 240, 240));
        txtnumVenta.setText("");
        txtConcepto.setText("");
        txtCaja.setText("");
        txtUsuario.setText("");
        txtHora.setText("");
        txtFecha.setText("");
        txtMonto.setText("");
    }
}
