/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AbrirCajaControl;
import Controlador.LoginControl;
import Controlador.ManejadorFechas;
import Modelo.FlujoCajaDAO;
import Modelo.UsuarioCajaDAO;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marce
 */
public class Login extends javax.swing.JFrame {

    int botonSeleccionado = 0;

    public Login() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        camposTransparentes();
    }

    public void camposTransparentes() {
        Color c = new Color(0, 0, 1, 0.01f);
        txtUsuario.setBackground(c);
        txtPass.setBackground(c);
        btnIngresar.setBackground(c);
        grupoBotones.add(btnCaja1);
        grupoBotones.add(btnCaja2);
        grupoBotones.add(btnVIP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSeleccionarCaja = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        btnVIP = new javax.swing.JToggleButton();
        btnCaja1 = new javax.swing.JToggleButton();
        btnCaja2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        grupoBotones = new javax.swing.ButtonGroup();
        customPanel2 = new Controlador.CustomPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        panelSeleccionarCaja.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INDIQUE SU CAJA");
        panelSeleccionarCaja.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        btnVIP.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btnVIP.setText("VIP");
        btnVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIPActionPerformed(evt);
            }
        });
        panelSeleccionarCaja.getContentPane().add(btnVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 80));

        btnCaja1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btnCaja1.setText("GENERAL 1");
        btnCaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaja1ActionPerformed(evt);
            }
        });
        panelSeleccionarCaja.getContentPane().add(btnCaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 80));

        btnCaja2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btnCaja2.setText("GENERAL 2");
        btnCaja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaja2ActionPerformed(evt);
            }
        });
        panelSeleccionarCaja.getContentPane().add(btnCaja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, 80));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelSeleccionarCaja.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 170, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("INGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelSeleccionarCaja.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 60));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customPanel2.setOpaque(false);
        customPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        customPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        txtUsuario.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        customPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 280, 40));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        customPanel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 190, 40));

        btnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresar.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        customPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 310, 80));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 0));
        jLabel13.setText("DISCOTECK");
        customPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MISTER JUERGA");
        customPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        txtPass.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        customPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 270, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabel3.setText("SALIR");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        customPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, 70));

        getContentPane().add(customPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        txtPass.requestFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        //173, 431
        try {
            String usuario = txtUsuario.getText().toUpperCase();
            String pass = String.valueOf(txtPass.getPassword()).toUpperCase();
            String fechaInicio = new FlujoCajaDAO().getFechaDeMaxIdFlujoDeUsuario(new LoginControl().getIdUsuarioConNombre(txtUsuario.getText().toUpperCase()));
            System.out.println(fechaInicio);
            int idFlujoCaja = new FlujoCajaDAO().getEstadoConFecha(new LoginControl().getIdUsuarioConNombre(txtUsuario.getText().toUpperCase()), fechaInicio);
            System.out.println(idFlujoCaja);
            int flag = 0;
            if (idFlujoCaja > 0) {
                flag++;
            }
            System.out.println(flag);
            System.out.println(idFlujoCaja);
            if (flag > 0) {
                //si ya se aperturo la caja entonces logearse normal
                if (new LoginControl().validar(usuario, pass)) {
                    //validar que ya haya seleccionado una caja despues de haber aperturado
                    //si ya selecciono una caja, este panel no debe aparecer                
                    Menu m = new Menu(usuario);
                    m.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(getRootPane(), "ERROR DE DATOS, VERIFICA TU USUARIO O CONTRASEÑA");
                }
            } else {
                //actualizar segun la caja que se seleccionó
                panelSeleccionarCaja.setVisible(true);
                panelSeleccionarCaja.setBounds(800, 300, 220, 490);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        try {

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        btnIngresar.doClick();
    }//GEN-LAST:event_txtPassActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int idUsuario = new LoginControl().getIdUsuarioConNombre(txtUsuario.getText().toUpperCase());
            System.out.println(idUsuario);
            if (botonSeleccionado > 0) {
                switch (botonSeleccionado) {
                    case 3:
                        //actualizar la tabla usuariocaja
                        if (new UsuarioCajaDAO().updateUsuarioCaja(3, idUsuario)) {
                            System.out.println("caja general 1");
                        }
                        break;
                    case 4:
                        if (new UsuarioCajaDAO().updateUsuarioCaja(4, idUsuario)) {
                            System.out.println("caja general 2");
                        }
                        break;
                    case 5:
                        if (new UsuarioCajaDAO().updateUsuarioCaja(5, idUsuario)) {
                            System.out.println("caja VIP");
                        }
                        break;
                }

                Menu m = new Menu(txtUsuario.getText().toUpperCase());
                m.setVisible(true);
                dispose();
                panelSeleccionarCaja.dispose();
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "SELECCIONE UNA CAJA");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelSeleccionarCaja.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaja1ActionPerformed
        if (btnCaja1.isSelected()) {
            botonSeleccionado = 3;
        }
    }//GEN-LAST:event_btnCaja1ActionPerformed

    private void btnCaja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaja2ActionPerformed
        if (btnCaja2.isSelected()) {
            botonSeleccionado = 4;
        }
    }//GEN-LAST:event_btnCaja2ActionPerformed

    private void btnVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIPActionPerformed
        if (btnVIP.isSelected()) {
            botonSeleccionado = 5;
        }
    }//GEN-LAST:event_btnVIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCaja1;
    private javax.swing.JToggleButton btnCaja2;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JToggleButton btnVIP;
    private Controlador.CustomPanel customPanel2;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JDialog panelSeleccionarCaja;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
