/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AbrirCajaControl;
import Controlador.Cronometro;
import Controlador.ManejadorFechas;
import Modelo.FlujoCaja;
import Modelo.FlujoCajaDAO;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ELMER_03
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu(String usuario) throws Exception {
        setUndecorated(true);
        initComponents();
        lblUsuario.setText(usuario);
        lblCaja.setText(new AbrirCajaControl().getCajaDeUsuario(usuario));
        Color c = new Color(0, 0, 1, 0.15f);
        this.setBackground(c);
        new Cronometro().iniciarCronometro(txtHora);
        lblFecha.setText(new ManejadorFechas().getFechaActual());
    }

    public Menu() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuOpciones = new javax.swing.JPopupMenu();
        MenuPrecios = new javax.swing.JMenuItem();
        btnVentas = new javax.swing.JButton();
        btnAnulaciones = new javax.swing.JButton();
        btnPagosPersonal = new javax.swing.JButton();
        btnAperturarCaja = new javax.swing.JButton();
        btnCerrarCaja = new javax.swing.JButton();
        btnGastos = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCaja = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblLogoIdSoft = new javax.swing.JLabel();

        MenuPrecios.setText("CONFIGURACIÓN");
        MenuPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPreciosActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuPrecios);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentas.setBackground(new java.awt.Color(102, 153, 255));
        btnVentas.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        btnVentas.setText("VENTAS");
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 250, 210));

        btnAnulaciones.setBackground(new java.awt.Color(153, 255, 153));
        btnAnulaciones.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnAnulaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anulaciones.png"))); // NOI18N
        btnAnulaciones.setText("ANULACIONES");
        btnAnulaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnulaciones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAnulaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnulaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnulacionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnulaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 250, 210));

        btnPagosPersonal.setBackground(new java.awt.Color(102, 255, 102));
        btnPagosPersonal.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnPagosPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagospersonal.png"))); // NOI18N
        btnPagosPersonal.setText("PAGOS PERSONAL");
        btnPagosPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagosPersonal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPagosPersonal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPagosPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagosPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 330, 250, 210));

        btnAperturarCaja.setBackground(new java.awt.Color(255, 51, 0));
        btnAperturarCaja.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnAperturarCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abrirCaja.png"))); // NOI18N
        btnAperturarCaja.setText("APERTURAR CAJA");
        btnAperturarCaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAperturarCaja.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAperturarCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAperturarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAperturarCajaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAperturarCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 250, 210));

        btnCerrarCaja.setBackground(new java.awt.Color(255, 153, 102));
        btnCerrarCaja.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnCerrarCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarCaja.png"))); // NOI18N
        btnCerrarCaja.setText("CERRAR CAJA");
        btnCerrarCaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarCaja.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCajaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 250, 210));

        btnGastos.setBackground(new java.awt.Color(255, 204, 51));
        btnGastos.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gastos.png"))); // NOI18N
        btnGastos.setText("GASTOS");
        btnGastos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGastos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGastos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 550, 250, 210));

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 0));
        jLabel13.setText("DISCOTECK");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel12.setText("DISCOTECK");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 0, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MISTER JUERGA");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel18.setText("MISTER JUERGA");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1010, 1920, 40));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setComponentPopupMenu(MenuOpciones);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/puerta-de-salida-abierta.png"))); // NOI18N
        lblSalir.setText("SALIR");
        lblSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 20, 100, 170));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CAJA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("grover987");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        lblFecha.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("FECHA");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 150, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USUARIO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblCaja.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lblCaja.setForeground(new java.awt.Color(255, 255, 255));
        lblCaja.setText("______");
        jPanel1.add(lblCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU PRINCIPAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 700, 80));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(0, 153, 204));
        txtHora.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setText("hora");
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 460, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 220));

        lblLogoIdSoft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoIdSoft.PNG"))); // NOI18N
        lblLogoIdSoft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoIdSoftMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogoIdSoft, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 800, -1, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        try {
            int flag = 0;
            FlujoCajaDAO fcdao = new FlujoCajaDAO();
            FlujoCaja fcaja = new FlujoCaja();
            int idFlujoCaja = fcdao.getIdFlujo(new AbrirCajaControl().getIdUsuario(lblUsuario.getText()), new AbrirCajaControl().getIdCaja(lblCaja.getText()));
            System.out.println("idflujo de caja: " + idFlujoCaja);
            fcaja = fcdao.obtener(idFlujoCaja);
//            if (fcaja.getIdFlujoCaja() == idFlujoCaja && fcaja.getEstado().equals("1")) {
//                flag++;
//            }
            if (idFlujoCaja != 0) {

                System.out.println("idCaja: " + fcaja.getIdCaja());

                if (fcaja.getIdCaja() == 5) {
                    VentasVIP vvip = new VentasVIP(lblUsuario.getText().toUpperCase());
                    vvip.setVisible(true);
                } else {
                    Ventas v = new Ventas(lblUsuario.getText().toUpperCase());
                    v.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "DEBE APERTURAR CAJA PARA REALIZAR VENTAS");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnAnulacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnulacionesActionPerformed
        try {
            Anulaciones a = new Anulaciones(lblUsuario.getText().toUpperCase());
            a.setVisible(true);
            //dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAnulacionesActionPerformed

    private void btnPagosPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosPersonalActionPerformed
        try {
            PagosPersonal a = new PagosPersonal(lblUsuario.getText().toUpperCase());
            a.setVisible(true);
            //dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPagosPersonalActionPerformed

    private void btnAperturarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAperturarCajaActionPerformed
        try {
            AbrirCaja a = new AbrirCaja(lblUsuario.getText().toUpperCase());
            a.setVisible(true);
            //dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAperturarCajaActionPerformed

    private void btnCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCajaActionPerformed
        try {
            int flag = 0;
            int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new AbrirCajaControl().getIdUsuario(lblUsuario.getText()), new AbrirCajaControl().getIdCaja(lblCaja.getText()));
            FlujoCajaDAO fcdao = new FlujoCajaDAO();
            for (FlujoCaja fc : fcdao.Listar()) {
                if (fc.getIdFlujoCaja() == idFlujoCaja && fc.getEstado().equals("1")) {
                    flag++;
                }
            }
            if (flag > 0) {
                CerrarCaja a = new CerrarCaja(lblUsuario.getText().toUpperCase());
                a.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "DEBE APERTURAR CAJA PARA REALIZAR EL CIERRE RESPECTIVO");
            }

            //dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCerrarCajaActionPerformed

    private void btnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosActionPerformed
        try {
            int flag = 0;
            int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new AbrirCajaControl().getIdUsuario(lblUsuario.getText()), new AbrirCajaControl().getIdCaja(lblCaja.getText()));
            FlujoCajaDAO fcdao = new FlujoCajaDAO();
            for (FlujoCaja fc : fcdao.Listar()) {
                if (fc.getIdFlujoCaja() == idFlujoCaja && fc.getEstado().equals("1")) {
                    flag++;
                }
            }
            if (flag > 0) {
                Gastos g = new Gastos(lblUsuario.getText().toUpperCase());
                g.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "DEBE APERTURAR CAJA PARA REALIZAR GASTOS");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGastosActionPerformed

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void MenuPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPreciosActionPerformed
        JOptionPane.showMessageDialog(getRootPane(), "ESTE ES EL  MENU DE CONFIGURACION DE PRECIOS DE PRODUCTOS MAS VENDIDOS");
    }//GEN-LAST:event_MenuPreciosActionPerformed

    private void lblLogoIdSoftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoIdSoftMouseClicked
        /* ABRIR NOTA DE PEDIDO */
        try {
            int flag = 0;
            int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new AbrirCajaControl().getIdUsuario(lblUsuario.getText()), new AbrirCajaControl().getIdCaja(lblCaja.getText()));
            FlujoCajaDAO fcdao = new FlujoCajaDAO();
            for (FlujoCaja fc : fcdao.Listar()) {
                if (fc.getIdFlujoCaja() == idFlujoCaja && fc.getEstado().equals("1")) {
                    flag++;
                }
            }

            if (flag > 0) {
                VentasNotaPedido vnp = new VentasNotaPedido(lblUsuario.getText());
                vnp.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "DEBE APERTURAR CAJA PARA COBRAR NOTAS DE PEDIDO");
            }

        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblLogoIdSoftMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu MenuOpciones;
    private javax.swing.JMenuItem MenuPrecios;
    private javax.swing.JButton btnAnulaciones;
    private javax.swing.JButton btnAperturarCaja;
    private javax.swing.JButton btnCerrarCaja;
    private javax.swing.JButton btnGastos;
    private javax.swing.JButton btnPagosPersonal;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCaja;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLogoIdSoft;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
