/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.PagonPersonalControl;
import Controlador.Validaciones;
import Modelo.UsuarioGastos;
import Modelo.UsuarioGastosDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Marce
 */
public class PagosPersonal extends javax.swing.JFrame {

    //DefaultTableModel modeloPersonal;
    public PagosPersonal(String usuario) throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        new PagonPersonalControl().titulosTabla(tblPersonal);
    }

    public PagosPersonal() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNumerico = new javax.swing.JDialog();
        txtPersonal1 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonal = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBonificacion = new javax.swing.JTextField();
        btnRealizarPago = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        txtPago = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDcto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMonto1 = new javax.swing.JTextField();
        btnPanelNumerico = new javax.swing.JButton();

        panelNumerico.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPersonal1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtPersonal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonal1ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(txtPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 80));

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton14.setText("7");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 100));

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton15.setText("8");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 110, 100));

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton16.setText("9");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 110, 100));

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton17.setText("4");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 100));

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton18.setText("5");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, 100));

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton19.setText("6");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, 100));

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton20.setText("1");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 110, 100));

        jButton21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton21.setText("2");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 110, 100));

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton22.setText("3");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 110, 100));

        jButton23.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton23.setText("0");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 100));

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton24.setText("<");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 110, 100));

        btnBuscar1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBuscar1.setText("ACEPTAR");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        panelNumerico.getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 350, 80));

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setText("PAGO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        tblPersonal.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        tblPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPersonal.setRowHeight(26);
        tblPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersonal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 510, 520));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setText("BONIFICACION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        txtBonificacion.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtBonificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtBonificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 180, -1));

        btnRealizarPago.setBackground(new java.awt.Color(0, 153, 0));
        btnRealizarPago.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnRealizarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarPago.setText("REALIZAR PAGO");
        btnRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 310, 90));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PAGOS PERSONAL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 150));

        jButton12.setText("REPORTE DE PAGOS");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 670, 310, 30));

        txtPago.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        getContentPane().add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 180, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setText("PERFIL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        txtPerfil.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        getContentPane().add(txtPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 180, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setText("DESCUENTO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        txtDcto.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        getContentPane().add(txtDcto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 180, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setText("MONTO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        txtMonto.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 180, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel10.setText("PENALIDAD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        txtMonto1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtMonto1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMonto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 180, -1));

        btnPanelNumerico.setText("C");
        btnPanelNumerico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelNumericoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPanelNumerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPagoActionPerformed
        try {
//            if (new Validaciones().validarCampoVacio(txtPersonal)) {
//                if (new Validaciones().validarCampoVacio(txtBonificacion)) {
//                    int fila = tblPersonal.getSelectedRow();
//                    int idUsuario = Integer.parseInt(tblPersonal.getValueAt(fila, 0).toString());
//                    //int idGasto = new PagonPersonalControl().getIdGasto(cmbConcepto.getSelectedItem().toString());
//                    double monto = Double.parseDouble(txtBonificacion.getText());
//                    UsuarioGastos ug = new UsuarioGastos();
//                    ug.setIdUsuario(idUsuario);
//                    //ug.setIdGastos(idGasto);
//                    ug.setMonto(monto);
//                    UsuarioGastosDAO ugdao = new UsuarioGastosDAO();
//                    if (ugdao.registrar(ug)) {
//                        JOptionPane.showMessageDialog(rootPane, "PAGO REGISTRADO");
//                        new PagonPersonalControl().limpiarCampos(txtPersonal, txtBonificacion, tblPersonal);
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(rootPane, "INGRESE MONTO DE PAGO");
//                    txtBonificacion.requestFocus();
//                }
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "INGRESE DNI DE PERSONAL");
//                txtPersonal.requestFocus();
//            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnRealizarPagoActionPerformed

    private void txtPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonal1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnPanelNumericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelNumericoActionPerformed
        panelNumerico.setVisible(true);
    }//GEN-LAST:event_btnPanelNumericoActionPerformed

    private void tblPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonalMouseClicked
        try {
            int fila = tblPersonal.getSelectedRow();
            int idPersonal = Integer.parseInt(tblPersonal.getValueAt(fila, 0).toString());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblPersonalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PagosPersonal().setVisible(true);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnPanelNumerico;
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog panelNumerico;
    private javax.swing.JTable tblPersonal;
    private javax.swing.JTextField txtBonificacion;
    private javax.swing.JTextField txtDcto;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMonto1;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtPerfil;
    private javax.swing.JTextField txtPersonal1;
    // End of variables declaration//GEN-END:variables
}
